export enum textTypes {
  TITLE_BOLD = 'TITLE_BOLD', //24px
  TITLE_REGULAR = 'TITLE_REGULAR',
  TITLE_LIGHT = 'TITLE_LIGHT',

  PARAGRAPH_BOLD = 'PARAGRAPH_BOLD', //20px
  PARAGRAPH_REGULAR = 'PARAGRAPH_REGULAR',
  PARAGRAPH_LIGHT = 'PARAGRAPH_LIGHT',

  BUTTON_BOLD = 'BUTTON_BOLD', //18px
  BUTTON_REGULAR = 'BUTTON_REGULAR',
  BUTTON_LIGHT = 'BUTTON_LIGHT',

  SUB_TITLE_BOLD = 'SUB_TITLE_BOLD', //14px
  SUB_TITLE_REGULAR = 'SUB_TITLE_REGULAR',
  SUB_TITLE_LIGHT = 'SUB_TITLE_LIGHT',

  PARAGRAPH_SMALL_BOLD = 'PARAGRAPH_SMALL_BOLD', //10px
  PARAGRAPH_SMALL_REGULAR = 'PARAGRAPH_SMALL_REGULAR',
  PARAGRAPH_SMALL_LIGHT = 'PARAGRAPH_SMALL_LIGHT',
}
